/*

lista de alumnos de la promocion 52 del LMJ

*/

import { writable } from "svelte/store";

export const alumnos52 = writable([
  {
    fullname: "nunes granatello jose manuel",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "garcia sanchez andres david",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gonzalez gomez robinson steve",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "guerrero paredes luisnel jesus",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "camacho pineda jhoan",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "rincon salas gustavo adolfo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "rivas rondon jesus manuel",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "sanchez jorge isaac",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "romero araujo eddy luz",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "cardenas fernandez genesis paola",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gomez contreras ronald jose",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "varela guzman oliver leonardo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moncada toledo jonathan gerardo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "guerrero diaz daniel alberto",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "diaz dugarte cinthya grisel",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "zambrano galvis greilis maireli",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "rosales pererira navor",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "sanchez contreras rosangelica",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "espinoza omaña gladys mariana",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "serrano pabon jose leandro",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "bastidas mendoza anderson david",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "avendaño zambrano lismar betzahi",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "varela peña zulibeth yujane",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "diaz ramirez alexandra ruby",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "rios sanchez josue lenin",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "medina ramirez jesus alejandro",
    sex: 1,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "hernandez gutierrez carmen victoria",
    sex: 0,
    seccion: "a",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pineda zambrano jose gregorio",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "quintero rosales maribel beatriz",
    sex: 0,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "mejia sanchez alex eudomar",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "infante rico salvatore paolo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moreno pernia wilmer leonardo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gutierrez labellarte emilio constantino",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "serrano cardona kenny alexander",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "mateus gelves jose leonel",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "sanchez sanchez jhosmer alberto",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "ortega alarcon denis enrique",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pinto nava anais aracelis",
    sex: 0,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moncada soto luis ricardo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "mejia villamizar daninzon jose",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "morales cambar roberto emiro",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pulido enyer alfredo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moreno colmenares adolfo alejandro",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "granados hernandez brayan david",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "virguez lopez richard andres",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "vivas agudelo layneker jose",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "garcia rodriguez jesus reinaldo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "arellano rincon carmelo jesus",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "fernandez aldana jael fabiola",
    sex: 0,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "davila gil patricial del valle",
    sex: 0,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "becerra moreno miguel angel",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "mejia rincon carlos ramon",
    sex: 1,
    seccion: "b",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pineda rubio arun antonio",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "zambrano castro jose francisco",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "zambrano marquez silvio alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gomez moreno oscar eduardo",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pineda garcia yusley karina",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "prada oblitas milena carolina",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "marquez garcia diego miguel",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "ontiveros mejias alberto jose",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "torres peñaloza israel alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "tortosa rivas felix rafael",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "cabarico marquez orlangy josue",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "puccini guerrero juliano jose",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "rangel palomino miguel arcangel",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moreno mirabal jesus salvador",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "franco chacon luis guillermo",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "chavez castillo kevin alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "echeto pestana carmen rosa",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "jaramillo ortiz jhon antony",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "neira reyes yonatha rogelio",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "suarez arce claudia vanessa",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "chacon monsalve genesis yubraska",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "paredes hernandez fanny alexandra",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gonzalez sanchez estiven jose david",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "chacon guillen neydis hersay",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "avendaño chacon jesus alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "contreras hernandez maria de los angeles",
    sex: 0,
    seccion: "c",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "contreras garcia jose alirio",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "martinez diaz yhony yair",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "caraballo rosario bryan jose",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "perez anaya maria gabriela",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "añez sandoval ramon fernando",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "barrera peñaloza cesar eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "garcia gutierrez christian miguel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "carrillo mora aleider alberto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "aguilar ordoñez danimir enmanuel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "araque chacon jose gregorio",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pulido navarro mary lisbeth",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "gandica contreras erick alexander",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "carrero araque antonio jose junior",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "chacon jaimes andres eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "chacon medina raimer alberto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "murillo acevedo yosman jose",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "marcano torrealba ambar nohemi",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "moreno silva santiago salomon",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "contreras hernandez maria angelica",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "castillo velazquez victor manuel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "camacho davila gloanys beltz",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "quintero chacon angelica paola",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "molina rondon luis eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "pabon perez oscar augusto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
  {
    fullname: "mora pacheco silbeth karina",
    sex: 0,
    seccion: "d",
    profile_picture: "img/logo-lmj.JPG",
  },
]);
