/*

lista de alumnos de la promocion 52 del LMJ

*/

import { writable } from "svelte/store";

export const alumnos52 = writable([
  {
    fullname: "nunes granatello jose manuel",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/nunes-granatello.jpg",
  },
  {
    fullname: "garcia sanchez andres david",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/garcia-sanchez.jpg",
  },
  {
    fullname: "gonzalez gomez robinson steve",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/gonzalez-gomez.jpg",
  },
  {
    fullname: "guerrero paredes luisnel jesus",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/guerrero-paredes.jpg",
  },
  {
    fullname: "camacho pineda jhoan",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/camacho-pineda.jpg",
  },
  {
    fullname: "rincon salas gustavo adolfo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/rincon-salas.jpg",
  },
  {
    fullname: "rivas rondon jesus manuel",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/rivas-rondon.jpg",
  },
  {
    fullname: "sanchez jorge isaac",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/sanchez.jpg",
  },
  {
    fullname: "romero araujo eddy luz",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/romero-araujo.jpg",
  },
  {
    fullname: "cardenas fernandez genesis paola",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/cardenas-fernandez.jpg",
  },
  {
    fullname: "gomez contreras ronald jose",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/gomez-contreras.jpg",
  },
  {
    fullname: "varela guzman oliver leonardo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/varela-guzman.jpg",
  },
  {
    fullname: "moncada toledo jonathan gerardo",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/moncada-toledo.jpg",
  },
  {
    fullname: "guerrero diaz daniel alberto",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/guerrero-diaz.jpg",
  },
  {
    fullname: "diaz dugarte cinthya grisel",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/diaz-dugarte.jpg",
  },
  {
    fullname: "zambrano galvis greilis maireli",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/zambrano-galviz.jpg",
  },
  {
    fullname: "rosales pererira navor",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/rosales-pereira.jpg",
  },
  {
    fullname: "sanchez contreras rosangelica",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/sanchez-contreras.jpg",
  },
  {
    fullname: "espinoza omaña gladys mariana",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/espinoza-omaña.jpg",
  },
  {
    fullname: "serrano pabon jose leandro",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/serrano-pabon.jpg",
  },
  {
    fullname: "bastidas mendoza anderson david",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/bastidas-mendoza.jpg",
  },
  {
    fullname: "avendaño zambrano lismar betzahi",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/avendaño-zambrano.jpg",
  },
  {
    fullname: "varela peña zulibeth yujane",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/varela-peña.jpg",
  },
  {
    fullname: "diaz ramirez alexandra ruby",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/diaz-ramirez.jpg",
  },
  {
    fullname: "rios sanchez josue lenin",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/rios-sanchez.jpg",
  },
  {
    fullname: "medina ramirez jesus alejandro",
    sex: 1,
    seccion: "a",
    profile_picture: "img/alumns/medina-ramirez.jpg",
  },
  {
    fullname: "hernandez gutierrez carmen victoria",
    sex: 0,
    seccion: "a",
    profile_picture: "img/alumns/hernandez-gutierrez.jpg",
  },
  {
    fullname: "pineda zambrano jose gregorio",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/pineda-zambrano.jpg",
  },
  {
    fullname: "quintero rosales maribel beatriz",
    sex: 0,
    seccion: "b",
    profile_picture: "img/alumns/quintero-rosales.jpg",
  },
  {
    fullname: "mejia sanchez alex eudomar",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/mejia-sanchez.jpg",
  },
  {
    fullname: "infante rico salvatore paolo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/infante-rico.jpg",
  },
  {
    fullname: "moreno pernia wilmer leonardo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/moreno-pernia.jpg",
  },
  {
    fullname: "gutierrez labellarte emilio constantino",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/gutierrez-labellarte.jpg",
  },
  {
    fullname: "serrano cardona kenny alexander",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/serrano-cardona.jpg",
  },
  {
    fullname: "mateus gelves jose leonel",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/mateus-gelves.jpg",
  },
  {
    fullname: "sanchez sanchez jhosmer alberto",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/sanchez-sanchez.jpg",
  },
  {
    fullname: "ortega alarcon denis enrique",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/ortega-alarcon.jpg",
  },
  {
    fullname: "pinto nava anais aracelis",
    sex: 0,
    seccion: "b",
    profile_picture: "img/alumns/pinto-nava.jpg",
  },
  {
    fullname: "moncada soto luis ricardo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/moncada-soto.jpg",
  },
  {
    fullname: "mejia villamizar daninzon jose",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/mejia-villamizar.jpg",
  },
  {
    fullname: "morales cambar roberto emiro",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/morales-cambar.jpg",
  },
  {
    fullname: "pulido enyer alfredo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/pulido.jpg",
  },
  {
    fullname: "moreno colmenares adolfo alejandro",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/moreno-colmenares.jpg",
  },
  {
    fullname: "granados hernandez brayan david",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/granados-hernandez.jpg",
  },
  {
    fullname: "virguez lopez richard andres",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/virguez-lopez.jpg",
  },
  {
    fullname: "vivas agudelo layneker jose",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/vivas-agudelo.jpg",
  },
  {
    fullname: "garcia rodriguez jesus reinaldo",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/garcia-rodriguez.jpg",
  },
  {
    fullname: "arellano rincon carmelo jesus",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/arellano-rincon.jpg",
  },
  {
    fullname: "fernandez aldana jael fabiola",
    sex: 0,
    seccion: "b",
    profile_picture: "img/alumns/fernandez-aldana.jpg",
  },
  {
    fullname: "davila gil patricial del valle",
    sex: 0,
    seccion: "b",
    profile_picture: "img/alumns/davila-gil.jpg",
  },
  {
    fullname: "becerra moreno miguel angel",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/becerra-moreno.jpg",
  },
  {
    fullname: "mejia rincon carlos ramon",
    sex: 1,
    seccion: "b",
    profile_picture: "img/alumns/mejia-rincon.jpg",
  },
  {
    fullname: "pineda rubio arun antonio",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/pineda-rubio.jpg",
  },
  {
    fullname: "zambrano castro jose francisco",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/zambrano-castro.jpg",
  },
  {
    fullname: "zambrano marquez silvio alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/zambrano-marquez.jpg",
  },
  {
    fullname: "gomez moreno oscar eduardo",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/gomez-moreno.jpg",
  },
  {
    fullname: "pineda garcia yusley karina",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/pineda-garcia.jpg",
  },
  {
    fullname: "prada oblitas milena carolina",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/prada-oblitas.jpg",
  },
  {
    fullname: "marquez garcia diego miguel",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/marquez-garcia.jpg",
  },
  {
    fullname: "ontiveros mejias alberto jose",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/ontiveros-mejias.jpg",
  },
  {
    fullname: "torres peñaloza israel alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/torres-peñaloza.jpg",
  },
  {
    fullname: "tortosa rivas felix rafael",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/tortosa-rivas.jpg",
  },
  {
    fullname: "cabarico marquez orlangy josue",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/cabarico-marquez.jpg",
  },
  {
    fullname: "puccini guerrero juliano jose",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/puccini-guerrero.jpg",
  },
  {
    fullname: "rangel palomino miguel arcangel",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/rangel-palomino.jpg",
  },
  {
    fullname: "moreno mirabal jesus salvador",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/moreno-mirabal.jpg",
  },
  {
    fullname: "franco chacon luis guillermo",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/franco-chacon.jpg",
  },
  {
    fullname: "chavez castillo kevin alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/chavez-castillo.jpg",
  },
  {
    fullname: "echeto pestana carmen rosa",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/echeto-pestana.jpg",
  },
  {
    fullname: "jaramillo ortiz jhon antony",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/jaramillo-ortiz.jpg",
  },
  {
    fullname: "neira reyes yonatha rogelio",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/neira-reyes.jpg",
  },
  {
    fullname: "suarez arce claudia vanessa",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/suarez-arce.jpg",
  },
  {
    fullname: "chacon monsalve genesis yubraska",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/chacon-monsalve.jpg",
  },
  {
    fullname: "paredes hernandez fanny alexandra",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/paredes-hernandez.jpg",
  },
  {
    fullname: "gonzalez sanchez estiven jose david",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/gonzalez-sanchez.jpg",
  },
  {
    fullname: "chacon guillen neydis hersay",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/chacon-guillen.jpg",
  },
  {
    fullname: "avendaño chacon jesus alejandro",
    sex: 1,
    seccion: "c",
    profile_picture: "img/alumns/avendaño-chacon.jpg",
  },
  {
    fullname: "contreras hernandez maria de los angeles",
    sex: 0,
    seccion: "c",
    profile_picture: "img/alumns/contreras-hernandez-mda.jpg",
  },
  {
    fullname: "contreras garcia jose alirio",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/contreras-garcia.jpg",
  },
  {
    fullname: "martinez diaz yhony yair",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/martinez-diaz.jpg",
  },
  {
    fullname: "caraballo rosario bryan jose",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/caraballo-rosario.jpg",
  },
  {
    fullname: "perez anaya maria gabriela",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/perez-anaya.jpg",
  },
  {
    fullname: "añez sandoval ramon fernando",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/añez-sandoval.jpg",
  },
  {
    fullname: "barrera peñaloza cesar eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/barrera-peñaloza.jpg",
  },
  {
    fullname: "garcia gutierres christian miguel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/garcia-gutierres.jpg",
  },
  {
    fullname: "carrillo mora aleider alberto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/carrillo-mora.jpg",
  },
  {
    fullname: "aguilar ordoñez danimir enmanuel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/aguilar-ordoñez.jpg",
  },
  {
    fullname: "araque chacon jose gregorio",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/araque-chacon.jpg",
  },
  {
    fullname: "pulido navarro mary lisbeth",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/pulido-navarro.jpg",
  },
  {
    fullname: "gandica contreras erick alexander",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/gandica-contreras.jpg",
  },
  {
    fullname: "carrero araque antonio jose junior",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/carrero-araque.jpg",
  },
  {
    fullname: "chacon jaimes andres eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/chacon-jaimes.jpg",
  },
  {
    fullname: "chacon medina raimer alberto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/chacon-medina.jpg",
  },
  {
    fullname: "murillo acevedo yosman jose",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/murillo-acevedo.jpg",
  },
  {
    fullname: "marcano torrealba ambar nohemi",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/marcano-torrealba.jpg",
  },
  {
    fullname: "moreno silva santiago salomon",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/moreno-silva.jpg",
  },
  {
    fullname: "contreras hernandez maria angelica",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/contreras-hernandez-ma.jpg",
  },
  {
    fullname: "castillo velazquez victor manuel",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/castillo-velazquez.jpg",
  },
  {
    fullname: "camacho davila gloanys beltz",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/camacho-davila.jpg",
  },
  {
    fullname: "quintero chacon angelica paola",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/quintero-chacon.jpg",
  },
  {
    fullname: "molina rondon luis eduardo",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/molina-rondon.jpg",
  },
  {
    fullname: "pabon perez oscar augusto",
    sex: 1,
    seccion: "d",
    profile_picture: "img/alumns/pabon-perez.jpg",
  },
  {
    fullname: "mora pacheco silbeth karina",
    sex: 0,
    seccion: "d",
    profile_picture: "img/alumns/mora-pacheco.jpg",
  },
]);
